In [99]:
#import dependencies
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [100]:
#list of all countries in gameDB
master_list_of_countries = ["Afghanistan" , "Aland Islands" , "Albania" , "Algeria" , "American Samoa" , "Andorra" , "Angola" , "Anguilla" , "Antarctica" , "Antigua and Barbuda" , "Argentina" , "Armenia" , "Aruba" , "Australia" , "Austria" , "Azerbaijan" , "Bahamas" , "Bahrain" , "Bangladesh" , "Barbados" , "Belarus" , "Belgium" , "Belize" , "Benin" , "Bermuda" , "Bhutan" , "Bolivia" , "Bonaire" , "Sint Eustatius and Saba" , "Bosnia and Herzegovina" , "Botswana" , "Bouvet Island" , "Brazil" , "British Indian Ocean Territory" , "British Virgin Islands" , "Brunei" , "Bulgaria" , "Burkina Faso" , "Burundi" , "Cambodia" , "Cameroon" , "Canada" , "Cape Verde" , "Cayman Islands" , "Central African Republic" , "Chad" , "Chile" , "China" , "Christmas Island" , "Cocos (Keeling) Islands" , "Colombia" , "Comoros" , "Cook Islands" , "Costa Rica" , "Croatia" , "Cuba" , "CuraÃ§ao" , "Cyprus" , "Czech Republic" , "DR Congo" , "Denmark" , "Djibouti" , "Dominica" , "Dominican Republic" , "Ecuador" , "Egypt" , "El Salvador" , "Equatorial Guinea" , "Eritrea" , "Estonia" , "Ethiopia" , "Falkland Islands" , "Faroe Islands" , "Fiji" , "Finland" , "France" , "French Guiana" , "French Polynesia" , "French Southern and Antarctic Lands" , "Gabon" , "Gambia" , "Georgia" , "Germany" , "Ghana" , "Gibraltar" , "Greece" , "Greenland" , "Grenada" , "Guadeloupe" , "Guam" , "Guatemala" , "Guernsey" , "Guinea" , "Guinea-Bissau" , "Guyana" , "Haiti" , "Heard Island and McDonald Islands" , "Honduras" , "Hong Kong" , "Hungary" , "Iceland" , "India" , "Indonesia" , "Iran" , "Iraq" , "Ireland" , "Isle of Man" , "Israel" , "Italy" , "Ivory Coast" , "Jamaica" , "Japan" , "Jersey" , "Jordan" , "Kazakhstan" , "Kenya" , "Kiribati" , "Kosovo" , "Kuwait" , "Kyrgyzstan" , "Laos" , "Latvia" , "Lebanon" , "Lesotho" , "Liberia" , "Libya" , "Liechtenstein" , "Lithuania" , "Luxembourg" , "Macau" , "Macedonia" , "Madagascar" , "Malawi" , "Malaysia" , "Maldives" , "Mali" , "Malta" , "Marshall Islands" , "Martinique" , "Mauritania" , "Mauritius" , "Mayotte" , "Mexico" , "Micronesia" , "Moldova" , "Monaco" , "Mongolia" , "Montenegro" , "Montserrat" , "Morocco" , "Mozambique" , "Myanmar" , "Namibia" , "Nauru" , "Nepal" , "Netherlands" , "New Caledonia" , "New Zealand" , "Nicaragua" , "Niger" , "Nigeria" , "Niue" , "Norfolk Island" , "North Korea" , "Northern Mariana Islands" , "Norway" , "Oman" , "Pakistan" , "Palau" , "Palestine" , "Panama" , "Papua New Guinea" , "Paraguay" , "Peru" , "Philippines" , "Pitcairn Islands" , "Poland" , "Portugal" , "Puerto Rico" , "Qatar" , "Republic of the Congo" , "Romania" , "Russia" , "Rwanda" , "RÃ©union" , "Saint BarthÃ©lemy" , "Saint Helena" , "Saint Kitts and Nevis" , "Saint Lucia" , "Saint Martin" , "Saint Pierre and Miquelon" , "Saint Vincent and the Grenadines" , "Samoa" , "San Marino" , "Saudi Arabia" , "Senegal" , "Serbia" , "Seychelles" , "Sierra Leone" , "Singapore" , "Sint Maarten" , "Slovakia" , "Slovenia" , "Solomon Islands" , "Somalia" , "South Africa" , "South Georgia" , "South Korea" , "South Sudan" , "Spain" , "Sri Lanka" , "Sudan" , "Suriname" , "Svalbard and Jan Mayen" , "Swaziland" , "Sweden" , "Switzerland" , "Syria" , "Taiwan" , "Tajikistan" , "Tanzania" , "Thailand" , "Timor-Leste" , "Togo" , "Tokelau" , "Tonga" , "Trinidad and Tobago" , "Tunisia" , "Turkey" , "Turkmenistan" , "Turks and Caicos Islands" , "Tuvalu" , "Uganda" , "Ukraine" , "United Arab Emirates" , "United Kingdom" , "United States" , "United States Minor Outlying Islands" , "United States Virgin Islands" , "Uruguay" , "Uzbekistan" , "Vanuatu" , "Vatican City" , "Venezuela" , "Vietnam" , "Wallis and Futuna" , "Western Sahara" , "Yemen" , "Zambia" , "Zimbabwe"]

In [101]:
#set the path to the html files
file_address = "HTML Files/html"
#it will iterate through all HTML files
html_counter = 1
#max number of html files
max_number_of_html = 15

#create lists for holding data
list_of_countries = []
list_of_games = []

#loop through the number of HTML files and load them into BeautifulSoup
while html_counter <= max_number_of_html:
    soup = BeautifulSoup(open(file_address + str(html_counter) + ".html", encoding='utf8'), "html.parser")
    #find all img tags in the HTML page
    list_of_soup = soup.findAll("img")
    for soup_entry in list_of_soup:
        #gameDB saves the flag country info in both "alt" and "data-lazy-alt" attributes in the img tag, so going to search both against the master list of countries
        player_country = soup_entry.get("alt")
        player_country_2 = soup_entry.get("data-lazy-alt")
        #if our code finds the country name in the master list of countries, iterate through to get the number of games owned by the owner
        if (player_country in master_list_of_countries):
            #get the number of games
            number_of_games = soup_entry.findNext().findNext().findNext().findNext().findNext().findNext().get_text()
            #some error capture, trying to convert number of games from string to int, if it fails, doesn't add country and number to our lists
            try:
                newstring = eachnumber.replace(",","")
                number_of_games_int = int(newstring)
                list_of_countries.append(player_country)
                list_of_games.append(number_of_games_int)
            except:
                print("oops, couldn't find number of games owned by this person!")
        elif (player_country_2 in master_list_of_countries):
            number_of_games = soup_entry.findNext().findNext().findNext().findNext().findNext().findNext().get_text()
            try:
                newstring = eachnumber.replace(",","")
                number_of_games_int = int(newstring)
                list_of_countries.append(player_country_2)
                list_of_games.append(number_of_games_int)
            except:
                print("oops, couldn't find number of games owned by this person!")
    html_counter = html_counter + 1

In [102]:
#create empty dataframe
game_db_data = pd.DataFrame()

#add our lists to dataframe
game_db_data["Countries"] = list_of_countries
game_db_data["Games Owned"] = list_of_games

#sum the games owned values, sort by descending
game_db_data = game_db_data.groupby(by="Countries").sum().reset_index()
game_db_data = game_db_data.sort_values("Games Owned", ascending=False)

game_db_data.to_csv("steam_sales_by_country.csv")

game_db_data

           Countries  Games Owned
78     United States      1390626
12             China       927084
22           Germany       671800
62            Russia       470260
69       South Korea       456824
..               ...          ...
48  Marshall Islands         6718
47             Malta         6718
46          Maldives         6718
44             Macau         6718
41           Lebanon         6718

[82 rows x 2 columns]